### ISSUE TITLE
Every URL I throw at it returns false

### ISSUE THREAD

**Issue by cwhittl** [samcleaver/phpGSB#16]
$phpgsb->doLookup("http://mybusinesspage.com.au") is dangerous when you go to https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=http://mybusinesspage.com.au

but is returning false which per the lookup example is safe.

Any ideas?

**Comment by samcleaver** [comment]
@cwhittl My reference site/script has been offline for a bit, have restarted it so will give it time to update and get back to you. Do other sites like gumblar.cn show as dangerous?

**Comment by samcleaver** [comment]
@cwhittl Just checked, I get a match for malware in my database. How long did you leave it updating? For reference mine is at:
http://gsbtool.beaver6813.com/ulookup.php

**Comment by cwhittl** [comment]
Sorry for the dead air, I had to move on and just call the api directly in
chunks of 500.   We're at the cusp of getting our URL shortener being
marked as dangerous by Google.

I will try to test again when I get this done.
Thanks

**Comment by samcleaver** [comment]
Funnily enough phpGSB was created for a URL shortener anti-spam in the first place, we managed to get it reasonably under control eventually when combined with a few other things. Shoot me an email (see profile) if you want some tips (as to how we did it).

**Comment by cwhittl** [comment]
Thanks Sam!
