### ISSUE TITLE
API 2.2 is not working anymore.

### ISSUE THREAD

**Issue by HolgerHees** [samcleaver/phpGSB#19]
It seams that google has switched off all version below 4.

I found more and more url which are marked as infected.

If I validate it on https://www.google.com/transparencyreport/safebrowsing/diagnostic it is not infected. So I guess that my database is not updated anymore.

And on https://developers.google.com/safe-browsing/ you can read that version 3 will be disabled in early 2017.

Any plans to support version 4?

**Comment by saippuakauppias** [comment]
https://github.com/saippuakauppias/safe-browsing
